# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: .

jobs:
# Please do not rename this job
  build-project:
    name: build deezee
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Run script
# uncomment the following lines if you want to add environment variables for this step
#        env:
#          MY_ENV_VAR: value-for-my-env-var
#          MY_SECRET_ENV_VAR: ${{ secrets.MY_SECRET }} # here you can find information how to create secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets
        run: python -m venv venv

      - name: Run script
# uncomment the following lines if you want to add environment variables for this step
#        env:
#          MY_ENV_VAR: value-for-my-env-var
#          MY_SECRET_ENV_VAR: ${{ secrets.MY_SECRET }} # here you can find information how to create secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets
        run: source venv/bin/activate

      - name: Run script
# uncomment the following lines if you want to add environment variables for this step
#        env:
#          MY_ENV_VAR: value-for-my-env-var
#          MY_SECRET_ENV_VAR: ${{ secrets.MY_SECRET }} # here you can find information how to create secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets
        run: npm i

      - name: Run script
# uncomment the following lines if you want to add environment variables for this step
#        env:
#          MY_ENV_VAR: value-for-my-env-var
#          MY_SECRET_ENV_VAR: ${{ secrets.MY_SECRET }} # here you can find information how to create secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets
        run: pip install -r requirements.txt

      - name: Run script
# uncomment the following lines if you want to add environment variables for this step
#        env:
#          MY_ENV_VAR: value-for-my-env-var
#          MY_SECRET_ENV_VAR: ${{ secrets.MY_SECRET }} # here you can find information how to create secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets
        run: gunicorn -w 2 app:app --daemon

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: 0a059489-0028-4c58-834a-ea77c4f75fa7
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/deezee/config.yaml
          action: upload
